# config.yaml - Single master configuration file

# Use --library <name> on command line to override default_library

# Set the default library here
current_library: "standard_fab"   # ‚Üê CHANGE THIS LINE

# change these paths as needed, please install fastp and mafft and set their paths here 
# set base_dir and output_folder 
# set previous_antibodies_db to the path of the previous antibodies database file (download from Haisun shared folder)

general:
  base_dir: "/Users/Hoan.Nguyen/ComBio/AbodyDisco"
  fastp_path: "/opt/anaconda3/bin/fastp"
  mafft_path: "/opt/anaconda3/bin/mafft"
  previous_antibodies_db: "/Users/Hoan.Nguyen/ComBio/AbodyDisco/data/All_mAb_20251106_FACS_BLI.xlsx"
  output_folder: "results"



libraries:
  standard_fab:
    vh_barcodes:
      VHH-IPI-101: "TGTGCCATTTCGGGTTCCGGTGGTAGCACCTAC"
      H1-69: "GGTGGTATTATTCCAATTTTTGGTACTGCTAAT"
      H3-23_A: "TCTTATATATCTTCATCTGGTTCTACTATTTAT"
      H5-51: "GGTATAATCTACCCCGGTGATTCTGATACTAGA"
      H3-7_A: "GCTAATATCAAACAAGAAGGTTCTGAAAAGTAT"
      H4-34: "GGTGAAATCAATCACTCTGGTTCCACCAAC"
      Scaffold16: "CGTCAGGCACCGGGTAAAGAACGTGAATTAGTCAGCGCC"
      VOB: "AGACAAGCTCCAGGTAAGGGTCGTGAATTAGTTGCCGGT"
      VH_BLAM: "TACAGACAAGCTCCAGGTAAGGGTCGTGAATTAGTTGCCGGT"
    vl_barcodes:
      K1-39: "GTCACGGTATCC"
      K3-15: "GTGACAGTCTCG"
      K4-1: "GTAACCGTGTCA"
      K3-20: "GTTACTGTTTCTTCTGCATCTACT"
    vh_barcode_region: [0, -1]
    vl_barcode_region: [-70, -1]

  fab4:
    vh_barcodes:
      VH1-69: "ACCACCCATCCATTCCAAACCTTGACCTGGAGCTTGTCTAACCCAAGAAAT"
      VH3-23: "GGCAGAAACCCATTCCAAACCCTTACCTGGAGCTTGTCTAACCCAAGACAT"
      VH4-30-4: "GTAACCAATCCATTCCAAACCCTTACCAGGTGGTTGTCTGATCCAAGACCA"
      VH5-51: "GATACCCATCCATTCCAAACCCTTACCTGGCATTTGTCTAACCCAACCAAT"
    vl_barcodes:
      VK1-39: "GAGGTGCAGTTG"
      VK3-15: "GAAGTTCAGTTA"
      VK4-1c: "GAAGTCCAACTT"
      VK2-28: "GAGGTTCAACTA"
    vh_barcode_region: [0, -1]
    vl_barcode_region: [-70, -1]

  vhh_full:
    vh_barcodes:
      VHH-IPI-101: "TGTGCCATTTCGGGTTCCGGTGGTAGCACCTAC"
      H1-69: "GGTGGTATTATTCCAATTTTTGGTACTGCTAAT"
      H1-46: "GGTATTATCAAACCATCTGGTGGTTCTACTTCT"
      H3-23_A: "TCTTATATATCTTCATCTGGTTCTACTATTTAT"
      H5-51: "GGTATAATCTACCCCGGTGATTCTGATACTAGA"
      H5-51_A: "GGTATAATCTACCCCGGTTATTCTGATACTAGA"
      H3-15: "GGTCGTATTAAGAGTAAAACCGATGGTGGTACTACTGAT"
      H3-7_A: "GCTAATATCAAACAAGAAGGTTCTGAAAAGTAT"
      H4-34: "GGTGAAATCAATCACTCTGGTTCCACCAAC"
      H4-39: "GGTTCTATATACTATTCTGGTTCAACTTAT"
      DEEPASH: "ACTCGCGGCTCAACCCGCAATGGCC"
      DEEPASH-R: "AACAACTTTCAACAGTTTCGGCACC"
      Scaffold16: "CGTCAGGCACCGGGTAAAGAACGTGAATTAGTCAGCGCC"
      VOB: "AGACAAGCTCCAGGTAAGGGTCGTGAATTAGTTGCCGGT"
      VH_BLAM: "TACAGACAAGCTCCAGGTAAGGGTCGTGAATTAGTTGCCGGT"
    vl_barcodes:
      K1-39: "GTCACGGTATCC"
      K3-15: "GTGACAGTCTCG"
      K4-1_C: "GTAACCGTGTCA"
      K3-20: "GTTACTGTTTCTTCTGCATCTACT"
    vh_barcode_region: [0, -1]
    vl_barcode_region: [0, -1]

processing:
  yyc_nt:
    - "TACTACTGC"
    - "TATTACTGC"
  wgq_nt:
    - "TGGGGACAA"

  hcdr3_min_len: 1
  hcdr3_max_len: 30
  read_count_min: 1
  read_freq_min: 0.0000001   # 1e-7 

  filters_include: []        # e.g. ["mPLXNB1"]
  filters_exclude: []        # e.g. ["VHH", "MACS"]

  skip_processed: false

combine:
  # Columns used for grouping in pivot table
  pivot_cols:
    - "cdr3_aa"
    - "vh_scaffold"
    - "vl_scaffold"
    - "cdr3_functional"

  # Name of the CDR3 column (used for liabilities, clustering, length filtering)
  cdr3_col: "cdr3_aa"

  # Filtering thresholds
  min_cdr3_len: 6
  max_cdr3_len: 30
  min_freq: 0.0001
  min_count: 5
  min_freq_sum: 0.0001
  min_reads_per_round: 5000
  remove_non_functional: true

  # Critical liabilities for rank adjustment
  critical_liabilities:
    - "l_glyco"
    - "l_RR"
    - "l_WW"
    - "l_cys"
    - "l_hydrophobic"
    - "l_neg_charge"
    - "l_pos_charge"
    - "l_arg"
    - "l_rmd"

  # Clustering
  greedy_cutoff: 0.85

  # Output
  top_leads_per_target: 10000

pick_leads:
  min_freq_first: 0.005
  min_freq_sum: 0.0005
  min_freq_table: 0.0001
  n_leads: 10000000
  critical_filtering: false
  priority_concentrations:
    - "4nM"
    - "20nM"
    - "100nM"
  dont_order_antigens: []

repeat_check:
  blosum_threshold: 0.8
  max_cdr3_len_blosum: 25
  n_workers: 8

fastp:
  qualified_quality_phred: 25
  unqualified_percent_limit: 20
  length_required: 50
  n_base_limit: 5
  correction: true
  overlap_len_require: 50
  overlap_diff_limit: 5
  thread: 8
  disable_adapter_trimming: true
  disable_trim_poly_g: true
